import { getDb } from "./db";
import { sql } from "drizzle-orm";

export async function seedFreeResources() {
  const db = await getDb();
  if (!db) {
    console.log("[Seed] Database not initialized");
    return;
  }

  const freeResources = [
    // Khan Academy
    {
      title: "Introduction aux Mathématiques",
      slug: "khan-academy-math-intro",
      description: "Cours complet de mathématiques du primaire au lycée",
      shortDescription: "Mathématiques fondamentales avec vidéos et exercices",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Khan+Academy",
      externalUrl: "https://www.khanacademy.org/math",
      platform: "khan_academy",
      category: "Mathématiques",
      level: "debutant",
      duration: 120,
      language: "fr",
      tags: "maths,fondamentaux,gratuit",
      rating: 4.8,
      enrollmentCount: 50000,
      isActive: true,
    },
    {
      title: "Statistiques et Probabilités",
      slug: "khan-academy-stats",
      description: "Cours complet de statistiques et probabilités",
      shortDescription: "Statistiques, probabilités et analyse de données",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Statistics",
      externalUrl: "https://www.khanacademy.org/math/statistics-probability",
      platform: "khan_academy",
      category: "Statistiques",
      level: "intermediaire",
      duration: 80,
      language: "fr",
      tags: "stats,probabilités,data",
      rating: 4.7,
      enrollmentCount: 35000,
      isActive: true,
    },
    {
      title: "Algèbre et Équations",
      slug: "khan-academy-algebra",
      description: "Cours complet d'algèbre linéaire et équations",
      shortDescription: "Algèbre, équations et résolution de problèmes",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Algebra",
      externalUrl: "https://www.khanacademy.org/math/algebra",
      platform: "khan_academy",
      category: "Mathématiques",
      level: "intermediaire",
      duration: 100,
      language: "fr",
      tags: "algèbre,mathématiques,équations",
      rating: 4.7,
      enrollmentCount: 42000,
      isActive: true,
    },
    {
      title: "Chimie Fondamentale",
      slug: "khan-academy-chemistry",
      description: "Cours de chimie générale et organique",
      shortDescription: "Chimie, réactions et molécules",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Chemistry",
      externalUrl: "https://www.khanacademy.org/science/chemistry",
      platform: "khan_academy",
      category: "Sciences",
      level: "intermediaire",
      duration: 110,
      language: "fr",
      tags: "chimie,sciences,réactions",
      rating: 4.6,
      enrollmentCount: 28000,
      isActive: true,
    },
    {
      title: "Biologie Cellulaire",
      slug: "khan-academy-biology",
      description: "Cours complet de biologie et biologie cellulaire",
      shortDescription: "Cellules, gènes et organismes vivants",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Biology",
      externalUrl: "https://www.khanacademy.org/science/biology",
      platform: "khan_academy",
      category: "Sciences",
      level: "intermediaire",
      duration: 130,
      language: "fr",
      tags: "biologie,sciences,cellules",
      rating: 4.7,
      enrollmentCount: 38000,
      isActive: true,
    },
    // MIT OpenCourseWare
    {
      title: "Introduction à l'Informatique",
      slug: "mit-ocw-cs-intro",
      description: "Cours d'informatique fondamentale du MIT",
      shortDescription: "Programmation et algorithmique de base",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=MIT+CS",
      externalUrl: "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
      platform: "mit_ocw",
      category: "Informatique",
      level: "debutant",
      duration: 100,
      language: "en",
      tags: "programmation,python,informatique",
      rating: 4.9,
      enrollmentCount: 100000,
      isActive: true,
    },
    {
      title: "Économétrie Appliquée",
      slug: "mit-ocw-econometrics",
      description: "Cours avancé d'économétrie du MIT",
      shortDescription: "Méthodes économétriques et applications",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Econometrics",
      externalUrl: "https://ocw.mit.edu/courses/14-32-econometrics-spring-2007/",
      platform: "mit_ocw",
      category: "Économie",
      level: "avance",
      duration: 90,
      language: "en",
      tags: "économétrie,statistiques,économie",
      rating: 4.6,
      enrollmentCount: 15000,
      isActive: true,
    },
    {
      title: "Calcul Différentiel et Intégral",
      slug: "mit-ocw-calculus",
      description: "Cours complet de calcul du MIT",
      shortDescription: "Dérivées, intégrales et applications",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Calculus",
      externalUrl: "https://ocw.mit.edu/courses/18-01-single-variable-calculus-fall-2006/",
      platform: "mit_ocw",
      category: "Mathématiques",
      level: "intermediaire",
      duration: 120,
      language: "en",
      tags: "calcul,mathématiques,analyse",
      rating: 4.8,
      enrollmentCount: 65000,
      isActive: true,
    },
    {
      title: "Algèbre Linéaire",
      slug: "mit-ocw-linear-algebra",
      description: "Cours d'algèbre linéaire du MIT",
      shortDescription: "Matrices, vecteurs et applications",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Linear+Algebra",
      externalUrl: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/",
      platform: "mit_ocw",
      category: "Mathématiques",
      level: "intermediaire",
      duration: 100,
      language: "en",
      tags: "algèbre-linéaire,mathématiques,matrices",
      rating: 4.9,
      enrollmentCount: 72000,
      isActive: true,
    },
    {
      title: "Physique Générale I",
      slug: "mit-ocw-physics-1",
      description: "Cours de physique générale du MIT",
      shortDescription: "Mécanique classique et dynamique",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Physics",
      externalUrl: "https://ocw.mit.edu/courses/8-01-physics-i-classical-mechanics-fall-2016/",
      platform: "mit_ocw",
      category: "Sciences",
      level: "intermediaire",
      duration: 140,
      language: "en",
      tags: "physique,mécanique,sciences",
      rating: 4.7,
      enrollmentCount: 48000,
      isActive: true,
    },
    // StatLearning
    {
      title: "Statistical Learning",
      slug: "statlearning-intro",
      description: "Introduction à l'apprentissage statistique",
      shortDescription: "Machine learning et statistiques appliquées",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=StatLearning",
      externalUrl: "https://www.statlearning.com/",
      platform: "statlearning",
      category: "Data Science",
      level: "intermediaire",
      duration: 150,
      language: "en",
      tags: "machine-learning,statistiques,data-science",
      rating: 4.8,
      enrollmentCount: 80000,
      isActive: true,
    },
    {
      title: "Deep Learning et Réseaux Neuronaux",
      slug: "statlearning-deeplearning",
      description: "Cours avancé sur le deep learning et les réseaux neuronaux",
      shortDescription: "Deep learning, CNN et RNN",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Deep+Learning",
      externalUrl: "https://www.statlearning.com/",
      platform: "statlearning",
      category: "Data Science",
      level: "avance",
      duration: 180,
      language: "en",
      tags: "deep-learning,neural-networks,ai",
      rating: 4.8,
      enrollmentCount: 52000,
      isActive: true,
    },
    // Open Learning Campus
    {
      title: "Suivi-Évaluation des Projets",
      slug: "olc-monitoring-evaluation",
      description: "Cours complet sur le suivi-évaluation",
      shortDescription: "M&E pour les projets de développement",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=M%26E",
      externalUrl: "https://olc.worldbank.org/",
      platform: "open_learning_campus",
      category: "Développement",
      level: "intermediaire",
      duration: 60,
      language: "fr",
      tags: "suivi-évaluation,développement,projets",
      rating: 4.5,
      enrollmentCount: 25000,
      isActive: true,
    },
    {
      title: "Politiques Publiques et Analyse d'Impact",
      slug: "olc-public-policy",
      description: "Analyse d'impact des politiques publiques",
      shortDescription: "Évaluation d'impact et politiques de développement",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Policy",
      externalUrl: "https://olc.worldbank.org/",
      platform: "open_learning_campus",
      category: "Politiques Publiques",
      level: "avance",
      duration: 80,
      language: "fr",
      tags: "politiques,impact,développement",
      rating: 4.7,
      enrollmentCount: 18000,
      isActive: true,
    },
    // Canal-U
    {
      title: "Économie Politique",
      slug: "canal-u-econ-politique",
      description: "Cours d'économie politique de l'université française",
      shortDescription: "Théories et pratiques de l'économie politique",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Econ",
      externalUrl: "https://www.canal-u.tv/",
      platform: "canal_u",
      category: "Économie",
      level: "intermediaire",
      duration: 70,
      language: "fr",
      tags: "économie,politique,théorie",
      rating: 4.4,
      enrollmentCount: 12000,
      isActive: true,
    },
    {
      title: "Méthodes Quantitatives en Sciences Sociales",
      slug: "canal-u-quantitative",
      description: "Méthodes quantitatives pour la recherche",
      shortDescription: "Statistiques et analyse quantitative",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Quantitative",
      externalUrl: "https://www.canal-u.tv/",
      platform: "canal_u",
      category: "Méthodologie",
      level: "avance",
      duration: 85,
      language: "fr",
      tags: "méthodologie,statistiques,recherche",
      rating: 4.6,
      enrollmentCount: 9000,
      isActive: true,
    },
    {
      title: "Histoire de l'Économie",
      slug: "canal-u-history-econ",
      description: "Cours d'histoire économique de l'université française",
      shortDescription: "Évolution historique de l'économie",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=History",
      externalUrl: "https://www.canal-u.tv/",
      platform: "canal_u",
      category: "Économie",
      level: "intermediaire",
      duration: 75,
      language: "fr",
      tags: "histoire,économie,sciences-sociales",
      rating: 4.5,
      enrollmentCount: 11000,
      isActive: true,
    },
    {
      title: "Sociologie et Changement Social",
      slug: "canal-u-sociology",
      description: "Cours de sociologie et analyse du changement social",
      shortDescription: "Sociologie, société et changements",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Sociology",
      externalUrl: "https://www.canal-u.tv/",
      platform: "canal_u",
      category: "Sciences Sociales",
      level: "intermediaire",
      duration: 80,
      language: "fr",
      tags: "sociologie,sciences-sociales,changement",
      rating: 4.4,
      enrollmentCount: 10000,
      isActive: true,
    },
    // OpenLearn
    {
      title: "Fondamentaux de la Gestion",
      slug: "openlearn-management-basics",
      description: "Cours gratuit de gestion et management de l'Open University",
      shortDescription: "Principes fondamentaux du management",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=OpenLearn",
      externalUrl: "https://www.open.edu/openlearn/",
      platform: "openlearn",
      category: "Gestion",
      level: "debutant",
      duration: 40,
      language: "en",
      tags: "management,gestion,entreprise",
      rating: 4.3,
      enrollmentCount: 22000,
      isActive: true,
    },
    {
      title: "Entrepreneuriat et Innovation",
      slug: "openlearn-entrepreneurship",
      description: "Cours gratuit sur l'entrepreneuriat et l'innovation",
      shortDescription: "Créer et gérer une entreprise",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Entrepreneurship",
      externalUrl: "https://www.open.edu/openlearn/",
      platform: "openlearn",
      category: "Entrepreneuriat",
      level: "intermediaire",
      duration: 45,
      language: "en",
      tags: "entrepreneuriat,innovation,business",
      rating: 4.4,
      enrollmentCount: 18000,
      isActive: true,
    },
    {
      title: "Développement Personnel et Leadership",
      slug: "openlearn-leadership",
      description: "Cours sur le leadership et le développement personnel",
      shortDescription: "Leadership, communication et développement",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Leadership",
      externalUrl: "https://www.open.edu/openlearn/",
      platform: "openlearn",
      category: "Développement Personnel",
      level: "debutant",
      duration: 35,
      language: "en",
      tags: "leadership,développement,communication",
      rating: 4.5,
      enrollmentCount: 21000,
      isActive: true,
    },
    // Saylor Academy
    {
      title: "Économie Microéconomique",
      slug: "saylor-microeconomics",
      description: "Cours complet de microéconomie avec certification gratuite",
      shortDescription: "Principes de microéconomie et théorie des prix",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Saylor",
      externalUrl: "https://www.saylor.org/",
      platform: "saylor_academy",
      category: "Économie",
      level: "intermediaire",
      duration: 110,
      language: "en",
      tags: "économie,microéconomie,certification",
      rating: 4.5,
      enrollmentCount: 18000,
      isActive: true,
    },
    {
      title: "Macroéconomie",
      slug: "saylor-macroeconomics",
      description: "Cours complet de macroéconomie avec certification",
      shortDescription: "Économie nationale et politique monétaire",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Macro",
      externalUrl: "https://www.saylor.org/",
      platform: "saylor_academy",
      category: "Économie",
      level: "intermediaire",
      duration: 100,
      language: "en",
      tags: "macroéconomie,économie,certification",
      rating: 4.6,
      enrollmentCount: 22000,
      isActive: true,
    },
    {
      title: "Comptabilité Financière",
      slug: "saylor-accounting",
      description: "Cours de comptabilité financière avec certification",
      shortDescription: "Principes comptables et états financiers",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Accounting",
      externalUrl: "https://www.saylor.org/",
      platform: "saylor_academy",
      category: "Finance",
      level: "intermediaire",
      duration: 90,
      language: "en",
      tags: "comptabilité,finance,certification",
      rating: 4.5,
      enrollmentCount: 19000,
      isActive: true,
    },
    // AUF - Campus Numérique Francophone
    {
      title: "Gouvernance et Politiques Publiques en Afrique",
      slug: "auf-governance-africa",
      description: "Ressources sur la gouvernance africaine et les politiques publiques",
      shortDescription: "Gouvernance et développement en Afrique",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=AUF",
      externalUrl: "https://www.auf.org/",
      platform: "auf",
      category: "Gouvernance",
      level: "avance",
      duration: 60,
      language: "fr",
      tags: "gouvernance,afrique,politiques,développement",
      rating: 4.4,
      enrollmentCount: 8000,
      isActive: true,
    },
    // UNESCO OER Commons
    {
      title: "Ressources Éducatives Libres en Sciences",
      slug: "unesco-oer-sciences",
      description: "Ressources éducatives libres en sciences sous licence Creative Commons",
      shortDescription: "Ressources OER en sciences naturelles",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=UNESCO+OER",
      externalUrl: "https://www.oercommons.org/",
      platform: "unesco_oer",
      category: "Sciences",
      level: "intermediaire",
      duration: 75,
      language: "en",
      tags: "sciences,ressources-libres,oer,creative-commons",
      rating: 4.5,
      enrollmentCount: 14000,
      isActive: true,
    },
    {
      title: "Ressources Éducatives Libres en Mathématiques",
      slug: "unesco-oer-math",
      description: "Ressources OER en mathématiques sous licence Creative Commons",
      shortDescription: "Ressources mathématiques libres",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Math+OER",
      externalUrl: "https://www.oercommons.org/",
      platform: "unesco_oer",
      category: "Mathématiques",
      level: "intermediaire",
      duration: 90,
      language: "en",
      tags: "mathématiques,oer,ressources-libres",
      rating: 4.6,
      enrollmentCount: 16000,
      isActive: true,
    },
    // Bookdown
    {
      title: "R pour l'Analyse Statistique",
      slug: "bookdown-r-statistics",
      description: "Manuel complet d'analyse statistique avec R en accès libre",
      shortDescription: "Programmation R et statistiques appliquées",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Bookdown",
      externalUrl: "https://bookdown.org/",
      platform: "bookdown",
      category: "Data Science",
      level: "intermediaire",
      duration: 120,
      language: "en",
      tags: "r,statistiques,programmation,data-science",
      rating: 4.7,
      enrollmentCount: 45000,
      isActive: true,
    },
    // FUN-MOOC
    {
      title: "Introduction à la Science des Données",
      slug: "fun-mooc-data-science",
      description: "MOOC gratuit sur les fondamentaux de la science des données",
      shortDescription: "Data science et machine learning pour débutants",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=FUN-MOOC",
      externalUrl: "https://www.fun-mooc.fr/",
      platform: "fun_mooc",
      category: "Data Science",
      level: "debutant",
      duration: 50,
      language: "fr",
      tags: "data-science,mooc,machine-learning,gratuit",
      rating: 4.6,
      enrollmentCount: 32000,
      isActive: true,
    },
    {
      title: "Python pour les Débutants",
      slug: "fun-mooc-python",
      description: "MOOC gratuit pour apprendre Python",
      shortDescription: "Programmation Python pour débutants",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=Python",
      externalUrl: "https://www.fun-mooc.fr/",
      platform: "fun_mooc",
      category: "Programmation",
      level: "debutant",
      duration: 60,
      language: "fr",
      tags: "python,programmation,mooc",
      rating: 4.7,
      enrollmentCount: 55000,
      isActive: true,
    },
    {
      title: "Bases de Données SQL",
      slug: "fun-mooc-sql",
      description: "MOOC sur les bases de données et SQL",
      shortDescription: "SQL et gestion de bases de données",
      thumbnailUrl: "https://via.placeholder.com/300x200?text=SQL",
      externalUrl: "https://www.fun-mooc.fr/",
      platform: "fun_mooc",
      category: "Programmation",
      level: "intermediaire",
      duration: 50,
      language: "fr",
      tags: "sql,bases-données,programmation",
      rating: 4.6,
      enrollmentCount: 28000,
      isActive: true,
    },
  ];

  try {
    for (const resource of freeResources) {
      await db.execute(
        sql`
          INSERT IGNORE INTO free_resources (
            title, slug, description, shortDescription, thumbnailUrl, externalUrl,
            platform, category, level, duration, language, tags, rating, enrollmentCount, isActive, createdAt, updatedAt
          ) VALUES (
            ${resource.title}, ${resource.slug}, ${resource.description}, ${resource.shortDescription},
            ${resource.thumbnailUrl}, ${resource.externalUrl}, ${resource.platform}, ${resource.category},
            ${resource.level}, ${resource.duration}, ${resource.language}, ${resource.tags},
            ${resource.rating}, ${resource.enrollmentCount}, ${resource.isActive}, NOW(), NOW()
          )
        `
      );
    }
    console.log("[Seed] Free resources seeded successfully");
  } catch (error: any) {
    if (error.message?.includes("Duplicate entry")) {
      console.log("[Seed] Free resources already exist, skipping");
    } else {
      console.error("[Seed] Error seeding free resources:", error);
    }
  }
}
